### ISSUE TITLE
xp bell curve

### ISSUE THREAD

**Issue by gpoulton** [InfiniteAxis/SmaugFUSS#15]
https://github.com/InfiniteAxis/SmaugFUSS/blob/master/src/fight.c#L3705 

Maybe I'm reading this wrong, but it seems like anyone who can average faster than 2000 seconds / level flies right under the radar and doesn't get any exp penalty at all?

The obvious fix would be to add a "else xp >> 5" at line 3725.

**Comment by Arthmoor** [comment]
Late reply, but thanks. This will be addressed with the next codebase update.
