### ISSUE TITLE
renumber bug

### ISSUE THREAD

**Issue by sigmareaver** [InfiniteAxis/SmaugFUSS#9]
Link: https://github.com/InfiniteAxis/SmaugFUSS/blob/master/src/renumber.c#L629
Bug: Renumber only renumbers the first reset in a room, and skips the rest.
Problem: renumber.c line 629
`for( treset = preset->first_reset; treset; treset = preset->next_reset )`
Solution: Change preset->next_reset to treset->next_reset
`for( treset = preset->first_reset; treset; treset = treset->next_reset )`

**Comment by Arthmoor** [comment]
Is 4 years later a bad thing? Who knows, but it's fixed now. Thanks.

**Comment by sigmareaver** [comment]
Better late than never I suppose. Haven’t played with a MUD in a long time.
